[package]
name = "bulletrl_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
bytemuck = "1.9.1"
byteorder = "1.4.3"
log = "0.4.17"
